<?php

	$cOption = $_GET['o'];
	
	switch($cOption) {
		case 1:
			echo 'You have selected Option 1.<br><br>Some text, some text, some text.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.';
			break;
		case 2:
			echo 'Option 2 has been selected!<br><br>Some text, some text, some text.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.';
			break;
		case 3:
			echo 'This is option 3!<br><br>Some text, some text, some text.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.<br>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc sagittis. Nulla facilisi. Nam eu eros. Nullam tempus, ligula ac ultricies molestie, lectus lorem convallis lorem, eget cursus metus augue eu nisl. Nulla lorem est, placerat vel, posuere at, consectetuer quis, massa. Sed consectetuer rhoncus dolor. Integer semper, dolor sed feugiat blandit, felis ipsum feugiat lacus, non vulputate mauris risus ornare turpis. Duis molestie magna sed massa. Aenean a metus. Aliquam erat volutpat. Duis nec risus quis dui hendrerit sagittis. Quisque venenatis dolor non est. Nunc vel libero vel magna pellentesque eleifend. Curabitur id massa. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent risus. Aliquam molestie magna a lorem molestie auctor.';
			break;
		default:
			echo 'Whoops, didn\'t understand that option: <i>'.$cOption.'</i>';
	}

?>